package priceCompare.backend.enums;

public enum Subcategory {
    KIPSPLAAT("Kipsplaat"),
    OSB_PLAAT("OSB-plaat"),
    VINEER("Vineer"),
    TSEMENTKIUDPLAAT("Tsementkiudplaat"),
    PUITKIUDPLAAT("Puitkiudplaat"),
    PUITLAASTPLAAT("Puitlaastplaat"),
    TUULETOKKEPLAAT("Tuuletõkeplaat"),
    KIPSKIUDPLAAT("Kipskiudplaat (Fermacell)"),
    MDF_PLAAT("MDF-plaat"),
    WEDI_PLAAT("WEDI plaat"),
    TYCROC_PLAAT("TYCROC plaat"),
    TEMPSI_PLAAT("TEMPSI plaat"),
    POORBETOON_BAUROC("Poorbetoon (bauroc)"),
    FIBO("Fibo"),
    OONESPLOKK("Õõnesplokk"),
    TELLIS("Tellis"),
    SILIKAATPLOKK("Silikaatplokk (silroc)"),
    LAKKAPLOKK("Lakkaplokk"),
    KERATERM("Keraterm"),
    VUNDAMENDIPLOKK("Vundamendiplokk"),
    TANAVAKIVI("Tänavakivi, teekivi"),
    KONNITEPLAAT("Kõnniteeplaat"),
    AAREKIVID("Äärekivid"),
    VIHMAVEERENN("Vihmaveerenn"),
    LOODUSKIVID("Looduskivid"),
    KIVIVILL("Kivivill"),
    KLAASVILL("Klaasvill"),
    EPS("EPS"),
    PIR("PIR"),
    XPS("XPS"),
    PRUSSID("Prussid"),
    LAUAD("Lauad"),
    HOOVELPUIT("Höövelpuit"),
    PAHTEL("Pahtel"),
    KROHV("Krohv"),
    MUURISEGU("Müürisegu"),
    PLAATIMISSEGU("Plaatimissegu"),
    TSEMENT("Tsement"),
    BETOON("Betoon"),
    LIIM("Liim"),
    VUUGITAIDE("Vuugitäide"),
    MUUD_SEGUD("Muud segud"),
    PORANDATASANDUS("Põrandatasandus"),
    VALISVOODRILAUD("Välisvoodrilaud"),
    PLAADID("Plaadid"),
    PROFIILID("Profiilid"),
    TARVIKUD("Tarvikud"),
    KIVI("Kivi"),
    TERAS("Teras"),
    ETERNIIT("Eterniit"),
    BITUUMEN("Bituumen"),
    PVC("PVC"),
    PC("PC"),
    RULLMATERJAL("Rullmaterjal"),
    KORSTNAD("Korstnad"),
    VARIKATUSED("Varikatused"),
    PLEKK("Plekk"),
    ARMATUUR("Armatuur"),
    KANDURID("Kandurid"),
    TALDMIKU_VORMID("Taldmiku vormid"),
    KILED("Kiled"),
    AURUTOKE("Aurustõke"),
    GEOTEKSTIIL("Geotekstiil"),
    KATUSE_ALUSKATE("Katuse aluskate"),
    KANGAD("Kangad"),
    KOORMAKATTED("Koormakatted"),
    EHITUSPAPP("Ehituspapp"),
    TAPEET("Tapeet"),
    NURGAD("Nurgad"),
    POSTIJALAD("Postijalad"),
    EHITUSKOBAD("Ehituskobad"),
    BETOONIHARGID("Betoonihargid"),
    PALGIKINGAD("Palgikingad"),
    PLEKKPROFIILID("Plekkprofiilid"),
    SISEUKSED("Siseuksed"),
    VALISUKSED("Välisuksed"),
    SAUNUKSED("Saunauksed"),
    UKSELENGID("Ukselengid"),
    POONINGULUUGID("Pööninguluugid"),
    KONTROLLLUUGID("Kontrollluugid"),
    AKNAD("Aknad"),
    KATUSEAKNAD("Katuseaknad"),
    AKNAPROFIILID("Aknaprofiilid"),
    AKNALAUAD("Aknalauad"),
    SISEVARVID("Sisevärvid"),
    VALISVARVID("Välisvärvid"),
    KRUNT("Krunt"),
    SISE("Sise"),
    VALIS("Välis"),
    PORAND("Põrand"),
    AVATAITED("Avatäited"),
    LAGI("Lagi"),
    VIIMISTLUSPLAADID("Viimistlusplaadid"),
    SEIN("Sein"),
    MAALRITEIP("Maalriteip"),
    TUULETOKKETEIP("Tuuletõkketeip"),
    UNIVERSAAL("Universaal"),
    LIIMID("Liimid"),
    HUDROISOLATSIOON("Hüdroisolatsioon"),
    HERMEETIKUD("Hermeetikud"),
    KANALISATSIOON("Kanalisatsioon"),
    VEETORUD("Veetorud"),
    VENTILATSIOON("Ventilatsioon"),
    VOOLIKUD("Voolikud"),
    LISATARVIKUD("Lisatarvikud"),
    LIIV("Liiv"),
    KRUUS("Kruus"),
    KILLUSTIK("Killustik"),
    KRUVID("Kruvid"),
    NAELAD("Naelad"),
    TUUBLID("Tüüblid"),
    POLDID("Poldid"),
    MUTRID("Mutrid"),
    NEEDID("Needid"),
    SEIBID("Seibid"),
    KLAMBRID("Klambrid"),
    ANKRUD("Ankrud"),
    KEERMELATID("Keermelatid"),
    MUUD("Muud"),
    KIPSITARVIKUD("Kipsitarvikud"),
    BAUROCI_TARVIKUD("Bauroci tarvikud"),
    FIBOTARVIKUD("Fibotarvikud");

    private final String displayName;

    Subcategory(String displayName) {
        this.displayName = displayName;
    }

    public String getDisplayName() {
        return displayName;
    }

    public static Subcategory fromDisplayName(String displayName) {
        for (Subcategory subcategory : Subcategory.values()) {
            if (subcategory.getDisplayName().equalsIgnoreCase(displayName)) {
                return subcategory;
            }
        }
        throw new IllegalArgumentException("Invalid subcategory display name: " + displayName);
    }
}
