package priceCompare.backend.stores.decora.service;

import static priceCompare.backend.enums.Subcategory.*;

import priceCompare.backend.enums.Subcategory;
import java.util.List;
import java.util.Map;

// Mappings of ematerjal.ee categories to decora.ee categories that klevu search api accepts
public class EmaterjalToDecoraCategoryMapping {
    public static final Map<Subcategory, List<String>> subcatMap = Map.<Subcategory, List<String>>ofEntries(
            Map.entry(KIPSPLAAT, List.of("Kipsplaadid")),
            Map.entry(OSB_PLAAT, List.of("Puitlaast- ja puitkiudplaadid")),
            Map.entry(VINEER, List.of("Vineerid")),
            Map.entry(TSEMENTKIUDPLAAT, List.of("Tsementplaadid")),
            Map.entry(PUITKIUDPLAAT, List.of("Puitlaast- ja puitkiudplaadid")),
            Map.entry(PUITLAASTPLAAT, List.of("Puitlaast- ja puitkiudplaadid")),
            Map.entry(KIPSKIUDPLAAT, List.of()),
            Map.entry(WEDI_PLAAT, List.of()),
            Map.entry(TYCROC_PLAAT, List.of("XPS ja PIR soojustusplaadid")),
            Map.entry(POORBETOON_BAUROC, List.of("Ehitusplokk")),
            Map.entry(FIBO, List.of("Ehitusplokk")),
            Map.entry(OONESPLOKK, List.of("Ehitusplokk")),
            Map.entry(SILIKAATPLOKK, List.of("Tellised")),
            Map.entry(LAKKAPLOKK, List.of()),
            Map.entry(KERATERM, List.of()),
            Map.entry(VUNDAMENDIPLOKK, List.of()),
            Map.entry(TELLIS, List.of("Tellised")),
            Map.entry(SILLUSED, List.of("Sillused")),
            Map.entry(TANAVAKIVI, List.of("Tänavakivid")),
            Map.entry(KONNITEPLAAT, List.of("Tänavakivid")),
            Map.entry(AAREKIVID, List.of("Tänavakivid")),
            Map.entry(VIHMAVEERENN, List.of("Tänavakivid")),
            Map.entry(KORSTNAD, List.of()),
            Map.entry(KIVIVILL, List.of("Kivivillad")),
            Map.entry(KLAASVILL, List.of("Klaasvillad")),
            Map.entry(TSELLUVILL, List.of("Tselluvill")),
            Map.entry(EPS, List.of("EPS-vahtpolüstüreen")),
            Map.entry(PIR, List.of("XPS ja PIR soojustusplaadid")),
            Map.entry(XPS, List.of("XPS ja PIR soojustusplaadid")),
            Map.entry(TUULETOKKEPLAAT, List.of("Tuuletõkkeplaadid")),
            Map.entry(PRUSSID, List.of("Saematerjal")),
            Map.entry(LAUAD, List.of("Saematerjal")),
            Map.entry(KALIBREERITUD_PRUSSID, List.of()),
            Map.entry(KALIBREERITUD_LAUAD, List.of()),
            Map.entry(HOOVELLAUAD, List.of("Höövelmaterjal")),
            Map.entry(SERVAMATA, List.of()),
            Map.entry(LIIMPUIT, List.of("Liimpuit")),
            Map.entry(PORANDALAUAD, List.of()),
            Map.entry(TERRASSILAUAD, List.of("Terrassilaud")),
            Map.entry(SISEVOODRILAUAD, List.of("Saunamaterjal", "Voordilaud")),
            Map.entry(PAHTEL, List.of("Valmispahtlid", "Pahtlid")),
            Map.entry(KROHV, List.of("Krohvid ja tarvikud")),
            Map.entry(MUURISEGU, List.of("Müürisegud ja betoonid")),
            Map.entry(PLAATIMISSEGU, List.of("Plaatimissegud")),
            Map.entry(VUUGISEGUD, List.of("Vuugisegud")),
            Map.entry(AHJUSEGUD, List.of("Ahjusegud")),
            Map.entry(TSEMENT, List.of("Müürisegud ja betoonid")),
            Map.entry(BETOON, List.of("Müürisegud ja betoonid")),
            Map.entry(LIIM, List.of("Müürisegud ja betoonid", "Fassaadisegud ja tarvikud")),
            Map.entry(PORANDATASANDUS, List.of("Põrandasegud ja tarvikud")),
            Map.entry(SEGUD_TARVIKUD, List.of("Fassaadisegud ja tarvikud")),
            Map.entry(SIDEAINED, List.of("Müürisegud ja betoonid")),
            Map.entry(PUITVOODRILAUAD, List.of()),
            Map.entry(TSEMENTVOODRILAUAD, List.of("Tsementplaadid")),
            Map.entry(PLASTVOODER, List.of("Plastvooder")),
            Map.entry(FASSAAD_PLAADID, List.of("Tsementplaadid")),
            Map.entry(PROFIILID, List.of("Tsementplaadid")),
            Map.entry(FASSAAD_TARVIKUD, List.of("Tsementplaadid")),
            Map.entry(KIVI, List.of()),
            Map.entry(TERAS, List.of()),
            Map.entry(ETERNIIT, List.of("Eterniitkatused")),
            Map.entry(BITUUMEN, List.of("Bituumenkatused")),
            Map.entry(PVC_PC, List.of("PVC katusematerjalid")),
            Map.entry(VIHMAVEESUSTEEMID, List.of("Vihmaveesüsteemid")),
            Map.entry(KATUSETARVIKUD, List.of("Katusematerjalid ja tarvikud")),
            Map.entry(EHITUSPAPP, List.of("Ehituspapid ja -paberid")),
            Map.entry(KANGAD, List.of("Tuuletõkke kangad")),
            Map.entry(KILED, List.of("Kattematerjalid")),
            Map.entry(AURUTOKE, List.of("Aurutõkked")),
            Map.entry(GEOTEKSTIIL, List.of("Geotekstiilid")),
            Map.entry(KATUSE_ALUSKATE, List.of("Katuse aluskatted")),
            Map.entry(ARMATUUR, List.of("Armatuur")),
            Map.entry(PLEKKPROFIILID, List.of("Ehitusmetall"))
    );
}
