package priceCompare.backend.stores.ehituseabc.service;

import priceCompare.backend.enums.Subcategory;

import java.util.List;
import java.util.Map;

import static priceCompare.backend.enums.Subcategory.*;

public class EmaterjalToEhituseAbcCategoryMapping {
    public static final Map<Subcategory, List<String>> categoryMap = Map.<Subcategory, List<String>>ofEntries(
            Map.entry(KIPSPLAAT, List.of("Standard kipsplaat", "Kõva kipsplaat", "Tuletõkke kipsplaat", "Niiskuskindlam kipsplaat", "Muu kipsplaat")),
            Map.entry(OSB_PLAAT, List.of("OSB-plaadid")),
            Map.entry(VINEER, List.of("Niiskuskindlam vineer", "Veekindel vineer", "Tavaline vineer")),
            Map.entry(TSEMENTKIUDPLAAT, List.of("Tsementplaadid")),
            Map.entry(PUITKIUDPLAAT, List.of("Puitlaastplaadid")),
            Map.entry(PUITLAASTPLAAT, List.of("Puitlaastplaadid")),
            Map.entry(KIPSKIUDPLAAT, List.of()),
            Map.entry(WEDI_PLAAT, List.of("Veekindel ehitusplaat")),
            Map.entry(TYCROC_PLAAT, List.of("Veekindel ehitusplaat")),

            Map.entry(POORBETOON_BAUROC, List.of("Kergbetoonplokid")),
            Map.entry(FIBO, List.of("Kergkruusaplokid")),
            Map.entry(OONESPLOKK, List.of("Betoonplokid")),
            Map.entry(SILIKAATPLOKK, List.of()),
            Map.entry(LAKKAPLOKK, List.of()),
            Map.entry(KERATERM, List.of()),
            Map.entry(VUNDAMENDIPLOKK, List.of()),
            Map.entry(TELLIS, List.of("Savitellised", "Šamott tellised")),
            Map.entry(SILLUSED, List.of("Kergsillused")),
            Map.entry(TANAVAKIVI, List.of("Kõnniteekivid, äärekivid")),
            Map.entry(KONNITEPLAAT, List.of("Kõnniteekivid, äärekivid")),
            Map.entry(AAREKIVID, List.of("Kõnniteekivid, äärekivid")),
            Map.entry(VIHMAVEERENN, List.of("Kõnniteekivid, äärekivid")),
            Map.entry(KORSTNAD, List.of("Korstnad")),

            Map.entry(KIVIVILL, List.of("Üldotstarbelised kivivillad", "Eriotstarbelised kivivillad", "Tuletõkke kivivillad", "Koormusttaluvad kivivillad")),
            Map.entry(KLAASVILL, List.of("Üldotstarbelised klaasvillad", "Eriotstarbelised klaasvillad", "Koormusttaluvad klaasvillad")),
            Map.entry(TSELLUVILL, List.of()),
            Map.entry(EPS,  List.of("Fassaadi polüstüreentooted", "Üldotstarbelised polüstüreentooted", "Koormusttaluvad polüstüreentooted")),
            Map.entry(PIR, List.of("Muud polüstüreentooted")),
            Map.entry(XPS, List.of("Muud polüstüreentooted")),
            Map.entry(TUULETOKKEPLAAT, List.of("Tuuletõkke klaasvillad")),

            Map.entry(PRUSSID, List.of("Prussid-lauad", "Immutatud saematerjal")),
            Map.entry(LAUAD, List.of("Prussid-lauad", "Immutatud saematerjal")),
            Map.entry(KALIBREERITUD_PRUSSID, List.of()),
            Map.entry(KALIBREERITUD_LAUAD, List.of()),
            Map.entry(HOOVELPRUSSID, List.of("Höövelmaterjalid", "Immutatud höövelmaterjal")),
            Map.entry(HOOVELLAUAD, List.of("Höövelmaterjalid", "Immutatud höövelmaterjal")),
            Map.entry(SERVAMATA, List.of()),
            Map.entry(LIIMPUIT, List.of()),
            Map.entry(PORANDALAUAD, List.of()),
            Map.entry(TERRASSILAUAD, List.of("Terrassilauad")),
            Map.entry(SISEVOODRILAUAD, List.of("Sisevoodrilauad")),

            Map.entry(PAHTEL, List.of("Seinatasandussegud", "Kips tasandussegud")),
            Map.entry(KROHV, List.of("Kips tasandussegud", "Krohvisegud", "Fassaadid")),
            Map.entry(MUURISEGU, List.of("Müürisegud")),
            Map.entry(PLAATIMISSEGU, List.of("Plaatimissegud")),
            Map.entry(VUUGISEGUD, List.of("Vuugisegud")),
            Map.entry(AHJUSEGUD, List.of("Tulekoldesegud")),
            Map.entry(TSEMENT, List.of("Tsemendid")),
            Map.entry(KUIVBETOON, List.of("Kuivbetoonid")),
            Map.entry(LIIM, List.of("Fassaadid")),
            Map.entry(PORANDATASANDUS, List.of("Põrandatasandussegud")),
            Map.entry(SEGUD_TARVIKUD, List.of("Müüri- ja segutööriistad")),
            Map.entry(SIDEAINED, List.of("Muud ehitussegud")),

            Map.entry(PUITVOODRILAUAD, List.of("Välisvoodrilauad")),
            Map.entry(TSEMENTVOODRILAUAD, List.of()),
            Map.entry(PLASTVOODER, List.of()),
            Map.entry(FASSAAD_PLAADID, List.of("Fassaadimaterjalid")),
            Map.entry(PROFIILID, List.of()),
            Map.entry(FASSAAD_TARVIKUD, List.of()),

            Map.entry(KIVI, List.of("Betoonkivikatused")),
            Map.entry(TERAS, List.of("Plekk katused")),
            Map.entry(ETERNIIT, List.of("Eterniit")),
            Map.entry(BITUUMEN, List.of("Bituumen katusekatte materjalid")),
            Map.entry(PVC_PC, List.of("PVC katusematerjalid")),
            Map.entry(VIHMAVEESUSTEEMID, List.of("Plekkvihmaveesüsteemid", "PVC vihmaveesüsteemid", "Vihmaveesüsteemid, sadeveesüsteemid")),
            Map.entry(KATUSETARVIKUD, List.of("Muud katusematerjalid ja tarvikud")),

            Map.entry(EHITUSPABER, List.of("Ehituspaberid")),
            Map.entry(KANGAD, List.of()),
            Map.entry(KILED, List.of("Ehituskiled")),
            Map.entry(AURUTOKE, List.of("Ehituskiled")),
            Map.entry(GEOTEKSTIIL, List.of("Ehituskiled")),
            Map.entry(KATUSE_ALUSKATE, List.of("Katuse aluskatted ja teibid")),
            Map.entry(ARMATUUR, List.of("Armatuurvõrgud", "Armatuurraud")),
            Map.entry(PLEKKPROFIILID, List.of("Metallkarkassid, kinnitused"))
    );

    public static final Map<Subcategory, String> categoryRootMap = Map.<Subcategory, String>ofEntries(
            Map.entry(KIPSPLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            Map.entry(OSB_PLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            Map.entry(VINEER, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            Map.entry(TSEMENTKIUDPLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            Map.entry(PUITKIUDPLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            Map.entry(PUITLAASTPLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            //Map.entry(KIPSKIUDPLAAT, null),
            Map.entry(WEDI_PLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            Map.entry(TYCROC_PLAAT, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),

            Map.entry(POORBETOON_BAUROC, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(FIBO, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(OONESPLOKK, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            //Map.entry(SILIKAATPLOKK, null),
            //Map.entry(LAKKAPLOKK, null),
            //Map.entry(KERATERM, null),
            //Map.entry(VUNDAMENDIPLOKK, null),
            Map.entry(TELLIS, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(SILLUSED, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(TANAVAKIVI, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(KONNITEPLAAT, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(AAREKIVID, "Ehitusmaterjalid;Ehituskivid, ehitusplokid, sillused;"),
            Map.entry(VIHMAVEERENN, "Ehitusmaterjalid;Vihmaveesüsteemid ja sadeveesüsteemid;"),
            Map.entry(KORSTNAD, "Ehitusmaterjalid;Korstnad;"),

            Map.entry(KIVIVILL, "Ehitusmaterjalid;Soojusisolatsioon;"),
            Map.entry(KLAASVILL, "Ehitusmaterjalid;Soojusisolatsioon;"),
            //Map.entry(TSELLUVILL, null),
            Map.entry(EPS, "Ehitusmaterjalid;Soojusisolatsioon;"),
            Map.entry(PIR, "Ehitusmaterjalid;Soojusisolatsioon;"),
            Map.entry(XPS, "Ehitusmaterjalid;Soojusisolatsioon;"),
            Map.entry(TUULETOKKEPLAAT, "Ehitusmaterjalid;Soojusisolatsioon;"),

            Map.entry(PRUSSID, "Ehitusmaterjalid;Ehituspuit;"),
            Map.entry(LAUAD, "Ehitusmaterjalid;Ehituspuit;"),
            //Map.entry(KALIBREERITUD_PRUSSID, null),
            //Map.entry(KALIBREERITUD_LAUAD, null),
            Map.entry(HOOVELPRUSSID, "Ehitusmaterjalid;Ehituspuit;"),
            Map.entry(HOOVELLAUAD, "Ehitusmaterjalid;Ehituspuit;"),
            //Map.entry(SERVAMATA, null),
            //Map.entry(LIIMPUIT, null),
            //Map.entry(PORANDALAUAD, null),
            Map.entry(TERRASSILAUAD, "Ehitusmaterjalid;Ehituspuit;"),
            Map.entry(SISEVOODRILAUAD, "Ehitusmaterjalid;Ehituspuit;"),

            Map.entry(PAHTEL, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(KROHV, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(MUURISEGU, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(PLAATIMISSEGU, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(VUUGISEGUD, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(AHJUSEGUD, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(TSEMENT, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(KUIVBETOON, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(LIIM, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(PORANDATASANDUS, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(SEGUD_TARVIKUD, "Ehitusmaterjalid;Ehitussegud;"),
            Map.entry(SIDEAINED, "Ehitusmaterjalid;Ehitussegud;"),

            Map.entry(PUITVOODRILAUAD, "Ehitusmaterjalid;Ehituspuit;"),
            //Map.entry(TSEMENTVOODRILAUAD, null),
            //Map.entry(PLASTVOODER, null),
            Map.entry(FASSAAD_PLAADID, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;"),
            //Map.entry(PROFIILID, null),
            //Map.entry(FASSAAD_TARVIKUD, null),

            Map.entry(KIVI, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(TERAS, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(ETERNIIT, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(BITUUMEN, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(PVC_PC, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(VIHMAVEESUSTEEMID, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(KATUSETARVIKUD, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),

            Map.entry(EHITUSPABER, "Ehitusmaterjalid;Hüdroisolatsioon;"),
            //Map.entry(KANGAD, null),
            Map.entry(KILED, "Ehitusmaterjalid;Hüdroisolatsioon;"),
            Map.entry(AURUTOKE, "Ehitusmaterjalid;Hüdroisolatsioon;"),
            Map.entry(GEOTEKSTIIL, "Ehitusmaterjalid;Hüdroisolatsioon;"),
            Map.entry(KATUSE_ALUSKATE, "Ehitusmaterjalid;Katusematerjalid, tarvikud;"),
            Map.entry(ARMATUUR, "Ehitusmaterjalid;Metallitooted;"),
            Map.entry(PLEKKPROFIILID, "Ehitusmaterjalid;Kergkonstruktsioon, ehitusplaadid;")
    );
}
