package priceCompare.backend.stores.ehomer.service;

import priceCompare.backend.enums.Subcategory;

import java.util.List;
import java.util.Map;

import static priceCompare.backend.enums.Subcategory.*;

// keeps links of every category page in puumarket.ee that we mapped to ematerjal.ee category
public class EmaterjalToEhomerCategoryMapping {
    public static final Map<Subcategory, List<String>> categoryMap = Map.<Subcategory, List<String>>ofEntries(
            Map.entry(KIPSPLAAT, List.of("kipsplaadid")),
            Map.entry(OSB_PLAAT, List.of("puitplaadid")),
            Map.entry(VINEER, List.of("vineer")),
            Map.entry(TSEMENTKIUDPLAAT, List.of("cetris%20tsementlaastplaadid")),
            Map.entry(PUITKIUDPLAAT, List.of("osb%203%20ja%20puitlaastplaadid")),
            Map.entry(PUITLAASTPLAAT, List.of("osb%203%20ja%20puitlaastplaadid")),
            Map.entry(KIPSKIUDPLAAT, List.of("fermacell")),
            Map.entry(WEDI_PLAAT, List.of()),
            Map.entry(TYCROC_PLAAT, List.of("tycroc%20plaadid")),
            Map.entry(POORBETOON_BAUROC, List.of("bauroc%20plokid%20ja%20tarvikud")),
            Map.entry(FIBO, List.of("fibo%20plokid%20ja%20tarvikud")),
            Map.entry(OONESPLOKK, List.of("oonesplokid")),
            Map.entry(SILIKAATPLOKK, List.of()),
            Map.entry(LAKKAPLOKK, List.of()),
            Map.entry(KERATERM, List.of()),
            Map.entry(VUNDAMENDIPLOKK, List.of()),
            Map.entry(TELLIS, List.of("telliskivid")),
            Map.entry(SILLUSED, List.of()),
            Map.entry(TANAVAKIVI, List.of()),
            Map.entry(KONNITEPLAAT, List.of()),
            Map.entry(AAREKIVID, List.of()),
            Map.entry(VIHMAVEERENN, List.of()),
            Map.entry(KORSTNAD, List.of()),
            Map.entry(KIVIVILL, List.of("kivivill")),
            Map.entry(KLAASVILL, List.of("klaasvill")),
            Map.entry(TSELLUVILL, List.of()),
            Map.entry(EPS, List.of("eps%20soojustus")),
            Map.entry(PIR, List.of("pir%20ja%20xps%20soojustusplaadid")),
            Map.entry(XPS, List.of("pir%20ja%20xps%20soojustusplaadid")),
            Map.entry(TUULETOKKEPLAAT, List.of("tuuletoke%20ja%20aluskatted")),
            Map.entry(PRUSSID, List.of("saematerjal%20prussid", "termopuit", "immutatud%20prussid")),
            Map.entry(LAUAD, List.of("saematerjal%20laud", "termopuit", "immutatud%20lauad")),
            Map.entry(KALIBREERITUD_PRUSSID, List.of()),
            Map.entry(KALIBREERITUD_LAUAD, List.of()),
            Map.entry(HOOVELPRUSSID, List.of("höövelmaterjal")),
            Map.entry(HOOVELLAUAD, List.of("höövelmaterjal")),
            Map.entry(SERVAMATA, List.of()),
            Map.entry(LIIMPUIT, List.of("liimpuit%20lvl")),
            Map.entry(PORANDALAUAD, List.of("porandalauad")),
            Map.entry(TERRASSILAUAD, List.of("terrassilauad")),
            Map.entry(SISEVOODRILAUAD, List.of("sisevoodrilaud", "sisevoodrilauad")),
            Map.entry(PAHTEL, List.of()),
            Map.entry(KROHV, List.of("krohvid")),
            Map.entry(MUURISEGU, List.of("muurisegud")),
            Map.entry(PLAATIMISSEGU, List.of("plaatimissegud")),
            Map.entry(VUUGISEGUD, List.of("plaatimissegud")),
            Map.entry(AHJUSEGUD, List.of("kutekollete%20segud")),
            Map.entry(TSEMENT, List.of("muurisegud")),
            Map.entry(KUIVBETOON, List.of("betoonid")),
            Map.entry(LIIM, List.of("muurisegud")),
            Map.entry(PORANDATASANDUS, List.of("porandasegud")),
            Map.entry(SEGUD_TARVIKUD, List.of()),
            Map.entry(SIDEAINED, List.of()),
            Map.entry(PUITVOODRILAUAD, List.of("valisvoodrilaud", "kuumolitatud%20laudis")),
            Map.entry(TSEMENTVOODRILAUAD, List.of()),
            Map.entry(PLASTVOODER, List.of()),
            Map.entry(FASSAAD_PLAADID, List.of("fassaadiplaat%20tempsi")),
            Map.entry(PROFIILID, List.of()),
            Map.entry(FASSAAD_TARVIKUD, List.of("kinnitusvahendid")),
            Map.entry(KIVI, List.of("kivikatus")),
            Map.entry(TERAS, List.of("plekk%20katus")),
            Map.entry(ETERNIIT, List.of("eterniit")),
            Map.entry(BITUUMEN, List.of("sbs%20bituumen%20rullid", "laineplaadid%20bituumen", "sindelkatus")),
            Map.entry(PVC_PC, List.of("valgusplaadid")),
            Map.entry(VIHMAVEESUSTEEMID, List.of()),
            Map.entry(KATUSETARVIKUD, List.of("aluskatted%20ja%20tarvikud%20katusele")),
            Map.entry(EHITUSPABER, List.of("ehituspapp%20ja%20kile")),
            Map.entry(KANGAD, List.of()),
            Map.entry(KILED, List.of("ehituspapp%20ja%20kile")),
            Map.entry(AURUTOKE, List.of("aurutoke")),
            Map.entry(GEOTEKSTIIL, List.of()),
            Map.entry(KATUSE_ALUSKATE, List.of("aluskatted")),
            Map.entry(VUNDAMENDIKATE, List.of()),
            Map.entry(ARMATUUR, List.of("armatuurteras", "armatuurvork")),
            Map.entry(PLEKKPROFIILID, List.of("karkass%20profiilid"))
    );
}
