package priceCompare.backend.stores.puumarket.service;

import priceCompare.backend.enums.Subcategory;

import java.util.List;
import java.util.Map;

import static priceCompare.backend.enums.Subcategory.*;

// keeps links of every category page in puumarket.ee that we mapped to ematerjal.ee category
public class EmaterjalToPuumarketCategoryMapping {
    public static final Map<Subcategory, List<String>> categoryMap = Map.<Subcategory, List<String>>ofEntries(
            Map.entry(KIPSPLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/kipsplaadid/")),
            Map.entry(OSB_PLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/osb-plaadid/", "https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/hobi-plaadid/")),
            Map.entry(VINEER, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/vineer-ja-veekindel-vineer/")),
            Map.entry(TSEMENTKIUDPLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/tsementplaadid/")),
            Map.entry(PUITKIUDPLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/puitehitusplaadid/")),
            Map.entry(PUITLAASTPLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/puitehitusplaadid/")),
            Map.entry(KIPSKIUDPLAAT, List.of()),
            Map.entry(WEDI_PLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/veekindel-ehitusplaat/")),
            Map.entry(TYCROC_PLAAT, List.of()),
            Map.entry(POORBETOON_BAUROC, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/plokid/")),
            Map.entry(FIBO, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/plokid/")),
            Map.entry(OONESPLOKK, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/plokid/")),
            Map.entry(SILIKAATPLOKK, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/plokid/")),
            Map.entry(LAKKAPLOKK, List.of()),
            Map.entry(KERATERM, List.of()),
            Map.entry(VUNDAMENDIPLOKK, List.of()),
            Map.entry(TELLIS, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/fassaadikivid/")),
            Map.entry(SILLUSED, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/sillused/")),
            Map.entry(TANAVAKIVI, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/tanavakivid/")),
            Map.entry(KONNITEPLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/tanavakivid/")),
            Map.entry(AAREKIVID, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/tanavakivid/")),
            Map.entry(VIHMAVEERENN, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/plokid-ja-kivid/tanavakivid/")),
            Map.entry(KORSTNAD, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/korstnad/")),
            Map.entry(KIVIVILL, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/soojustus/kivivill/")),
            Map.entry(KLAASVILL, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/soojustus/klaasvill/")),
            Map.entry(TSELLUVILL, List.of()),
            Map.entry(EPS, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/soojustus/vahtpolustureen/")),
            Map.entry(PIR, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/soojustus/pir-soojustusplaadid/")),
            Map.entry(XPS, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/soojustus/xps-soojustus/")),
            Map.entry(TUULETOKKEPLAAT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/ehitusplaadid/tuuletokkeplaadid/")),
            Map.entry(PRUSSID, List.of("https://puumarket.ee/tootekategooria/puit/saematerjal/kuivatatud-prussid/", "https://puumarket.ee/tootekategooria/puit/saematerjal/kuivatamata-prussid/", "https://puumarket.ee/tootekategooria/puit/immutatud-puit/prussid/")),
            Map.entry(LAUAD, List.of("https://puumarket.ee/tootekategooria/puit/saematerjal/kuivatatud-lauad/", "https://puumarket.ee/tootekategooria/puit/saematerjal/kuivatamata-lauad/", "https://puumarket.ee/tootekategooria/puit/immutatud-puit/lauad/")),
            Map.entry(KALIBREERITUD_PRUSSID, List.of("https://puumarket.ee/tootekategooria/puit/saematerjal/kuivatatud-prussid/")),
            Map.entry(KALIBREERITUD_LAUAD, List.of()),
            Map.entry(HOOVELPRUSSID, List.of("https://puumarket.ee/tootekategooria/puit/hoovelmaterjal/hoovelprussid/", "https://puumarket.ee/tootekategooria/puit/immutatud-puit/hoovelpuit/")),
            Map.entry(HOOVELLAUAD, List.of("https://puumarket.ee/tootekategooria/puit/hoovelmaterjal/silehooveldatud-lauad/", "https://puumarket.ee/tootekategooria/puit/hoovelmaterjal/peensaetud-hoovellauad/", "https://puumarket.ee/tootekategooria/puit/hoovelmaterjal/viimistletud-hoovellauad/", "https://puumarket.ee/tootekategooria/puit/immutatud-puit/hoovelpuit/")),
            Map.entry(SERVAMATA, List.of("https://puumarket.ee/tootekategooria/puit/tislerimaterjalid/servamata-materjal/")),
            Map.entry(LIIMPUIT, List.of("https://puumarket.ee/tootekategooria/puit/liimpuit/liimpuitkilbid/", "https://puumarket.ee/tootekategooria/puit/liimpuit/liimpuittalad/", "https://puumarket.ee/tootekategooria/puit/liimpuit/lvl-liimkihtpuit/", "https://puumarket.ee/tootekategooria/puit/liimpuit/ristkihtpuitplaadid/")),
            Map.entry(PORANDALAUAD, List.of("https://puumarket.ee/tootekategooria/puit/porandalauad/naturaalsed-porandalauad/", "https://puumarket.ee/tootekategooria/puit/porandalauad/viimistletud-porandalauad/")),
            Map.entry(TERRASSILAUAD, List.of("https://puumarket.ee/tootekategooria/terrass/terrassilauad/immutatud-terrassilauad/", "https://puumarket.ee/tootekategooria/terrass/terrassilauad/naturaalsest-lehisest-terrassilauad/", "https://puumarket.ee/tootekategooria/terrass/terrassilauad/viimistletud-terrassilauad/", "https://puumarket.ee/tootekategooria/puit/termotoodeldud-puit/termotoodeldud-terrassilauad/")),
            Map.entry(SISEVOODRILAUAD, List.of("https://puumarket.ee/tootekategooria/puit/sisevoodrilauad/naturaalsed-sisevoodrilauad/", "https://puumarket.ee/tootekategooria/puit/sisevoodrilauad/servamata-sisevoodrilauad/", "https://puumarket.ee/tootekategooria/puit/sisevoodrilauad/viimistletud-sisevoodrilauad/", "https://puumarket.ee/tootekategooria/puit/termotoodeldud-puit/termotoodeldud-sisevoodrilauad/")),
            Map.entry(PAHTEL, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/pahtlid-ja-krundid/")),
            Map.entry(KROHV, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/krohvisegud/")),
            Map.entry(MUURISEGU, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/muurisegud/")),
            Map.entry(PLAATIMISSEGU, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/plaatimissegud/")),
            Map.entry(VUUGISEGUD, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/porandasegud/")),
            Map.entry(AHJUSEGUD, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/muud-segud/")),
            Map.entry(TSEMENT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/liiv-tsement-betoon/")),
            Map.entry(KUIVBETOON, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/liiv-tsement-betoon/")),
            Map.entry(LIIM, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/liimisegud/")),
            Map.entry(PORANDATASANDUS, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/porandasegud/")),
            Map.entry(SEGUD_TARVIKUD, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/tarvikud-segud/")),
            Map.entry(SIDEAINED, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/segud/liiv-kruus/")),
            Map.entry(PUITVOODRILAUAD, List.of("https://puumarket.ee/tootekategooria/puit/valisvoodrilauad/naturaalsed-valisvoodrilauad/", "https://puumarket.ee/tootekategooria/puit/valisvoodrilauad/krunditud-valisvoodrilauad/", "https://puumarket.ee/tootekategooria/puit/valisvoodrilauad/varvitud-valisvoodrilauad/", "https://puumarket.ee/tootekategooria/puit/termotoodeldud-puit/valisvoodrilauad-termotoodeldud/")),
            Map.entry(TSEMENTVOODRILAUAD, List.of()),
            Map.entry(PLASTVOODER, List.of()),
            Map.entry(FASSAAD_PLAADID, List.of()),
            Map.entry(PROFIILID, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/fassaad/fassaadiprofiilid/")),
            Map.entry(FASSAAD_TARVIKUD, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/fassaad/tarvikud-fassaadile/")),
            Map.entry(KIVI, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/kivikatused/")),
            Map.entry(TERAS, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/teraskatused/")),
            Map.entry(ETERNIIT, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/eterniitkatused/")),
            Map.entry(BITUUMEN, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/bituumensindelkatused/", "https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/bituumenkatuseplaadid/", "https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/katuse-rullmaterjal/")),
            Map.entry(PVC_PC, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/pvc-katuseplaadid/", "https://puumarket.ee/tootekategooria/ehitusmaterjalid/katused/pc-katuseplaadid/", "https://puumarket.ee/tootekategooria/terrass/terrassikatused/laineplaadid/", "https://puumarket.ee/tootekategooria/terrass/terrassikatused/trapetsplaadid/")),
            Map.entry(VIHMAVEESUSTEEMID, List.of()),
            Map.entry(KATUSETARVIKUD, List.of()),
            Map.entry(EHITUSPABER, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/ehituspapp/")),
            Map.entry(KANGAD, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/tuuletokkekangad/")),
            Map.entry(KILED, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/kiled/")),
            Map.entry(AURUTOKE, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/aurutokked/")),
            Map.entry(GEOTEKSTIIL, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/geotekstiilid/")),
            Map.entry(KATUSE_ALUSKATE, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/katuse-aluskatted/")),
            Map.entry(VUNDAMENDIKATE, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/kattematerjalid/vundamendikatted/")),
            Map.entry(ARMATUUR, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/karkass-ja-armatuur/armatuur/")),
            Map.entry(PLEKKPROFIILID, List.of("https://puumarket.ee/tootekategooria/ehitusmaterjalid/karkass-ja-armatuur/karkass/"))
    );
}
