package priceCompare.backend.stores.krauta.service;

import static priceCompare.backend.enums.Subcategory.*;

import priceCompare.backend.enums.Subcategory;
import java.util.List;
import java.util.Map;

public class EmaterjalToKrautaCategoryMapping {
    public static final Map<Subcategory, List<String>> subcatMap = Map.<Subcategory, List<String>>ofEntries(
            Map.entry(KIPSPLAAT, List.of("Kipsplaadid")),
            Map.entry(OSB_PLAAT, List.of("OSB-plaadid", "Puitlaastplaadid")),
            Map.entry(VINEER, List.of("Ehitusvineer")),
            Map.entry(TSEMENTKIUDPLAAT, List.of("Tsementlaastplaadid")),
            Map.entry(PUITKIUDPLAAT, List.of("Puitlaastplaadid", "puitkiudplaadid")),
            Map.entry(PUITLAASTPLAAT, List.of("Puitlaastplaadid")),
            Map.entry(KIPSKIUDPLAAT, List.of()),
            Map.entry(WEDI_PLAAT, List.of()),
            Map.entry(TYCROC_PLAAT, List.of("Tsementlaastplaadid")),
            Map.entry(POORBETOON_BAUROC, List.of("Ehitusplokid")),
            Map.entry(FIBO, List.of("Ehitusplokid")),
            Map.entry(OONESPLOKK, List.of("Ehitusplokid")),
            Map.entry(SILIKAATPLOKK, List.of("Ehitusplokid")),
            Map.entry(LAKKAPLOKK, List.of("Ehitusplokid")),
            Map.entry(KERATERM, List.of("Ehitusplokid")),
            Map.entry(VUNDAMENDIPLOKK, List.of("Ehitusplokid")),
            Map.entry(TELLIS, List.of("Tellised")),
            Map.entry(SILLUSED, List.of()),
            Map.entry(TANAVAKIVI, List.of("Tänavaplaadid")),
            Map.entry(KONNITEPLAAT, List.of("Tänavaplaadid")),
            Map.entry(AAREKIVID, List.of("Tänavaplaadid")),
            Map.entry(VIHMAVEERENN, List.of("Tänavaplaadid")),
            Map.entry(KORSTNAD, List.of("Korstnad")),
            Map.entry(KIVIVILL, List.of("Kivivill")),
            Map.entry(KLAASVILL, List.of("Klaasvill, ökovill")),
            Map.entry(TSELLUVILL, List.of("Klaasvill, ökovill")),
            Map.entry(EPS, List.of("EPS-isolatsioon", "Vahtplast isolatsioon")),
            Map.entry(PIR, List.of("Polüuretaanplaadid")),
            Map.entry(XPS, List.of("XPS isolatsioon")),
            Map.entry(TUULETOKKEPLAAT, List.of()),
            Map.entry(PRUSSID, List.of("Hööveldamata puitprussid")),
            Map.entry(LAUAD, List.of("Puidust kahekordse lõikega lauad")),
            Map.entry(KALIBREERITUD_PRUSSID, List.of()),
            Map.entry(KALIBREERITUD_LAUAD, List.of()),
            Map.entry(HOOVELPRUSSID, List.of("Hööveldatud puitprussid")),
            Map.entry(HOOVELLAUAD, List.of("Puidust kahekordse lõikega lauad")),
            Map.entry(SERVAMATA, List.of()),
            Map.entry(LIIMPUIT, List.of("Liimpuitplaadid")),
            Map.entry(PORANDALAUAD, List.of("Ehitusplaadid, aknalauad, lauaplaadid")),
            Map.entry(TERRASSILAUAD, List.of("Terrassilauad ja tarvikud")),
            Map.entry(SISEVOODRILAUAD, List.of("Sisevoodrilauad")),
            Map.entry(PAHTEL, List.of("Pahtel")),
            Map.entry(KROHV, List.of("Krohvisegud")),
            Map.entry(MUURISEGU, List.of("Müürisegud")),
            Map.entry(PLAATIMISSEGU, List.of("Plaadi-ja muu liim")),
            Map.entry(VUUGISEGUD, List.of("Vuugisegud")),
            Map.entry(AHJUSEGUD, List.of("Puistematerjal")),
            Map.entry(TSEMENT, List.of("Tsement ja paigaldussegud")),
            Map.entry(KUIVBETOON, List.of("Kuivbetoon")),
            Map.entry(LIIM, List.of("Plaadi-ja muu liim")),
            Map.entry(PORANDATASANDUS, List.of("Tasandussegud")),
            Map.entry(SEGUD_TARVIKUD, List.of("Ehitusmaterjalide tarvikud")),
            Map.entry(SIDEAINED, List.of("Killustik, kruus, liiv, savi")),
            Map.entry(PUITVOODRILAUAD, List.of("Voodrilauad")),
            Map.entry(TSEMENTVOODRILAUAD, List.of()),
            Map.entry(PLASTVOODER, List.of("Plastist välisvoodrilauad")),
            Map.entry(FASSAAD_PLAADID, List.of("Voodrilauad, plaadid")),
            Map.entry(PROFIILID, List.of()),
            Map.entry(FASSAAD_TARVIKUD, List.of()),
            Map.entry(KIVI, List.of("Katusekivid")),
            Map.entry(TERAS, List.of("Lehtteras")),
            Map.entry(ETERNIIT, List.of("Asbestivabad eterniitplaadid")),
            Map.entry(BITUUMEN, List.of("Bituumenkate, ruberoid jm")),
            Map.entry(PVC_PC, List.of("PVC-plaadid")),
            Map.entry(VIHMAVEESUSTEEMID, List.of("Vihmaveesüsteemi tarvikud")),
            Map.entry(KATUSETARVIKUD, List.of("Katusekatted")),
            Map.entry(EHITUSPABER, List.of("Isolatsiooniplaadid ja islatsioonifooliumid")),
            Map.entry(KANGAD, List.of("Kiled, kaitsekangad")),
            Map.entry(KILED, List.of("Kiled, kaitsekangad")),
            Map.entry(AURUTOKE, List.of("Isolatsiooniplaadid ja islatsioonifooliumid")),
            Map.entry(GEOTEKSTIIL, List.of("Kiled, kaitsekangad")),
            Map.entry(KATUSE_ALUSKATE, List.of("Kiled, kaitsekangad")),
            Map.entry(ARMATUUR, List.of("Armatuur")),
            Map.entry(PLEKKPROFIILID, List.of("Seinakarkassid ja profiilid"))
    );
}
