# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Backend CI Pipeline

on:
  push:
    paths:
      - "backend/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "backend/**"
    branches:
      - main
# github actions
permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0

    - name: Give execute permissions to gradlew bin
      run: chmod +x gradlew
      working-directory: ./backend

    - name: Build Backend with Gradle Wrapper
      run: ./gradlew build #--debug #remove comment to see detailed logs of tests, gradle build runs tests too
      working-directory: ./backend

    - name: Log in to Docker Hub
      if: success()
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      if: success()
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:${{ github.sha }} .
      working-directory: ./backend

    - name: Push Docker image
      if: success()
      run: docker push ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:${{ github.sha }}

    - name: Tag Docker image as latest
      if: success()
      run: docker tag ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:latest

    - name: Push Docker image with latest tag
      if: success()
      run: docker push ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:latest

  merge-release:
    if: github.event.pull_request.merged == true || github.event_name == 'push' && github.ref == 'refs/heads/main'  # only runs on push events to main
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for merged release
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:release-${{ steps.date.outputs.date }} .
        working-directory: ./backend

      - name: Push Docker image for merged release
        run: docker push ${{ secrets.DOCKER_USERNAME }}/price-compare-backend:release-${{ steps.date.outputs.date }}