# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Frontend CI Pipeline

on:
  push:
    paths:
      - "frontend/**"
    branches: [ "main" ]
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main
# github actions
permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
       
      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
       
      - name: Install dependencies
        run: npm install
        working-directory: ./frontend
        
      - name: Run tests
        run: npm test
        env:
          CI: true
        working-directory: ./frontend
        
      - name: Generate build
        run: npm run build
        working-directory: ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:${{ github.sha }} .
        working-directory: ./frontend

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:${{ github.sha }}

      - name: Tag Docker image as latest
        if: success()
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:latest

      - name: Push Docker image with latest tag
        if: success()
        run: docker push ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:latest

  merge-release:
    if: github.event.pull_request.merged == true || github.event_name == 'push' && github.ref == 'refs/heads/main'  # only runs on push events to main
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%d-%m-%Y')"

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image for merged release
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:release-${{ steps.date.outputs.date }} .
        working-directory: ./frontend

      - name: Push Docker image for merged release
        run: docker push ${{ secrets.DOCKER_USERNAME }}/price-compare-frontend:release-${{ steps.date.outputs.date }}

      - name: Install SSH Key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Docker image to EC2
        run: |
            ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_INSTANCE_IP }} << 'EOF'
            docker pull ematerjalee/price-compare-backend:latest
            docker stop $(docker ps -q --filter "ancestor=$(docker images --format '{{.Repository}}:{{.Tag}}' | grep frontend)") || true
            docker run -d -p 3000:80 ematerjalee/price-compare-frontend:latest
            docker system prune -a -f
            EOF